### ISSUE TITLE
Eyelids?

### ISSUE THREAD

**Issue by CreateRemoteThread** [TwinLizzie/Sylvie-2021#3]
What's your thinking around the eyelids? Have you had any successful experiments in this area?

I'm thinking of shrinking (overall) the eyeball/eyelid portion of the eyemech to create a gap between plastic and silicone, then casting a second silicone eyelid and attaching it to the silicone face. Does that sound viable?

**Comment by TwinLizzie** [comment]
Hi there,

Yes, the new face model is already updated and fixed in the Blender file. Basically the problem with the current eyelid is that it's too wide open. There also needs to be a small 'air bubble' just below the the eyebrows in order to ensure a proper fold and minimum blinking-motor effort, which was also adjusted in the current core.

I haven't cast this new silicone face yet, however, as I'm currently busy with leg balancing and the walking algorithm, which is going to be officially tested in about 2-3 days.

Once the demo video of the leg balancing and first steps is released, I'll get onto printing, casting, painting and rigging the new silicone face, with some improvements in the mechanics of the mouth and eyebrows, too. It would probably save a lot of money and effort just to wait a little bit.

**Comment by CreateRemoteThread** [comment]
I think I understand what you mean by "too wide open".

When you say air bubble, do you mean simply thinning the skin above and below the (silicone) eyelids, so when the (eyemech) eyelids withdraw, there is room for them to retract in a natural manner, as per the following diagram, or did you mean something else?

![image](https://user-images.githubusercontent.com/5186279/167298596-240ee77e-ec98-4ca0-9d91-96dda0576a84.png)

Great work on all of this, really appreciate you making this excellent work public.

**Comment by TwinLizzie** [comment]
Yes, you got it right. Those are exactly the changes I made in the latest Blender model. 

Still need to cast and test it. Luckily I've already finished all soldering work on both robot legs. Thought I'd take the extra effort to make sure it's perfect so that I don't have to go back and redo anything in future. 

New animatronic head coming soon this month after balancing and first steps test.
